Use full LTO, update dependencies & CI

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,10 +1,15 @@
 name: Build
 
-on: [ push, pull_request ]
+on:
+  pull_request:
+  push:
+    paths-ignore:
+      - '*.md'
+      - 'LICENSE*'
+  workflow_dispatch:
 
 env:
   BUILD_PROFILE: release-lto
-  CARGO_BIN_NAME: nodtool
   CARGO_TARGET_DIR: target
 
 jobs:
@@ -79,7 +84,9 @@ jobs:
         run: cargo test --release
 
   build:
-    name: Build
+    name: Build nodtool
+    env:
+      CARGO_BIN_NAME: nodtool
     strategy:
       matrix:
         include:
@@ -88,11 +95,11 @@ jobs:
             name: linux-x86_64
             build: zigbuild
             features: asm
-#          - platform: ubuntu-latest
-#            target: i686-unknown-linux-musl
-#            name: linux-i686
-#            build: zigbuild
-#            features: asm
+          - platform: ubuntu-latest
+            target: i686-unknown-linux-musl
+            name: linux-i686
+            build: zigbuild
+            features: asm
           - platform: ubuntu-latest
             target: aarch64-unknown-linux-musl
             name: linux-aarch64
@@ -102,6 +109,11 @@ jobs:
             target: armv7-unknown-linux-musleabi
             name: linux-armv7l
             build: zigbuild
+            features: default
+          - platform: windows-latest
+            target: i686-pc-windows-msvc
+            name: windows-x86
+            build: build
             features: default
           - platform: windows-latest
             target: x86_64-pc-windows-msvc
@@ -135,20 +147,20 @@ jobs:
           sudo apt-get -y install ${{ matrix.packages }}
       - name: Install cargo-zigbuild
         if: matrix.build == 'zigbuild'
-        run: pip install ziglang==0.11.0 cargo-zigbuild==0.18.3
+        run: pip install ziglang==0.13.0 cargo-zigbuild==0.19.1
       - name: Setup Rust toolchain
-        uses: dtolnay/rust-toolchain@nightly
+        uses: dtolnay/rust-toolchain@stable
         with:
           targets: ${{ matrix.target }}
       - name: Cargo build
-        run: cargo ${{ matrix.build }} --profile ${{ env.BUILD_PROFILE }} --target ${{ matrix.target }} --bin ${{ env.CARGO_BIN_NAME }} --features ${{ matrix.features }}
+        run: >
+          cargo ${{ matrix.build }} --profile ${{ env.BUILD_PROFILE }} --target ${{ matrix.target }}
+          --bin ${{ env.CARGO_BIN_NAME }} --features ${{ matrix.features }}
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ matrix.name }}
+          name: ${{ env.CARGO_BIN_NAME }}-${{ matrix.name }}
           path: |
-            ${{ env.CARGO_TARGET_DIR }}/${{ env.BUILD_PROFILE }}/${{ env.CARGO_BIN_NAME }}
-            ${{ env.CARGO_TARGET_DIR }}/${{ env.BUILD_PROFILE }}/${{ env.CARGO_BIN_NAME }}.exe
             ${{ env.CARGO_TARGET_DIR }}/${{ matrix.target }}/${{ env.BUILD_PROFILE }}/${{ env.CARGO_BIN_NAME }}
             ${{ env.CARGO_TARGET_DIR }}/${{ matrix.target }}/${{ env.BUILD_PROFILE }}/${{ env.CARGO_BIN_NAME }}.exe
           if-no-files-found: error
@@ -159,6 +171,22 @@ jobs:
     runs-on: ubuntu-latest
     needs: [ build ]
     steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Check git tag against Cargo version
+        shell: bash
+        run: |
+          set -eou pipefail
+          tag='${{github.ref}}'
+          tag="${tag#refs/tags/}"
+          for file in */Cargo.toml; do
+            version=$(grep '^version' $file | head -1 | awk -F' = ' '{print $2}' | tr -d '"')
+            version="v$version"
+            if [ "$tag" != "$version" ]; then
+              echo "::error::Git tag doesn't match the Cargo version! ($tag != $version)"
+              exit 1
+            fi
+          done
       - name: Download artifacts
         uses: actions/download-artifact@v4
         with:
@@ -166,12 +194,26 @@ jobs:
       - name: Rename artifacts
         working-directory: artifacts
         run: |
+          set -euo pipefail
           mkdir ../out
-          for i in */*/$BUILD_PROFILE/$CARGO_BIN_NAME*; do
-            mv "$i" "../out/$(sed -E "s/([^/]+)\/[^/]+\/$BUILD_PROFILE\/($CARGO_BIN_NAME)/\2-\1/" <<< "$i")"
+          for dir in */; do
+            for file in "$dir"*; do
+              base=$(basename "$file")
+              name="${base%.*}"
+              ext="${base##*.}"
+              if [ "$ext" = "$base" ]; then
+                  ext=""
+              else
+                  ext=".$ext"
+              fi
+              arch="${dir%/}" # remove trailing slash
+              arch="${arch##"$name-"}" # remove bin name
+              dst="../out/${name}-${arch}${ext}"
+              mv "$file" "$dst"
+            done
           done
           ls -R ../out
       - name: Release
-        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
+        uses: softprops/action-gh-release@v2
         with:
           files: out/*
