Use workspace keys in Cargo.toml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -11,6 +11,7 @@ on:
 env:
   BUILD_PROFILE: release-lto
   CARGO_TARGET_DIR: target
+  CARGO_INCREMENTAL: 0
 
 jobs:
   check:
@@ -18,7 +19,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        toolchain: [ stable, 1.73.0, nightly ]
+        toolchain: [ stable, 1.74.0, nightly ]
       fail-fast: false
     env:
       RUSTFLAGS: -D warnings
@@ -179,14 +180,12 @@ jobs:
           set -eou pipefail
           tag='${{github.ref}}'
           tag="${tag#refs/tags/}"
-          for file in */Cargo.toml; do
-            version=$(grep '^version' $file | head -1 | awk -F' = ' '{print $2}' | tr -d '"')
-            version="v$version"
-            if [ "$tag" != "$version" ]; then
-              echo "::error::Git tag doesn't match the Cargo version! ($tag != $version)"
-              exit 1
-            fi
-          done
+          version=$(grep '^version' Cargo.toml | head -1 | awk -F' = ' '{print $2}' | tr -d '"')
+          version="v$version"
+          if [ "$tag" != "$version" ]; then
+            echo "::error::Git tag doesn't match the Cargo version! ($tag != $version)"
+            exit 1
+          fi
       - name: Download artifacts
         uses: actions/download-artifact@v4
         with:
@@ -217,3 +216,5 @@ jobs:
         uses: softprops/action-gh-release@v2
         with:
           files: out/*
+          draft: true
+          generate_release_notes: true
